---
- name: Check if httpd is installed
  hosts: all
  become: true
  tasks:
    - name: Check if httpd is installed
      command: rpm -qa | grep httpd
      register: httpd_status
      ignore_errors: yes

    - name: Check if httpd is running
      systemd:
        name: httpd
        state: started
        enabled: yes
      register: httpd_service
      
    - name: Print httpd status
      debug:
        msg: >-
          {{
            "Installed: " + httpd_status.stdout_lines[0] if httpd_status.rc == 0 else "Not Installed"
          }}
          {{
            "Running: " + httpd_service.state if httpd_service.changed else "Not Running"
          }}
