---
- name: Check if httpd is installed
  hosts: all
  become: true
  tasks:
    - name: Check if httpd is installed
      command: rpm -qa | grep httpd
      register: httpd_status
      ignore_errors: yes
      
    - name: Print httpd status
      debug:
        msg: >-
          {{
            "httpd installed" + httpd_status.stdout_lines[0] if httpd_status.rc == 0 else "httpd not Installed"
          }}
