---
- name: Check if httpd is installed
  hosts: all
  become: true
  tasks:
    - name: Check if httpd is installed
      command: rpm -qa | grep httpd
      register: httpd_status
      ignore_errors: yes

    - name: Print httpd packages
      debug:
        msg: "{{ item }}"
      loop: "{{ httpd_status.stdout_lines }}"
      when: item is search('^httpd')
