---
- hosts: all
  gather_facts: false
  tasks:
  become: true
  become_user: root
  - name: Install httpd package
    ansible.builtin.package:
      name: httpd
      state: latest
  - name: Start httpd service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
