---
- hosts: all
  gather_facts: false
  tasks:
  - name: Install httpd package
    ansible.builtin.package:
      name: httpd
      state: latest
    become: true
    become_user: root
  - name: latest index.html file is present
    copy:
      dest: /var/www/html/index.html
      content: |
        Hi, the Apache server is working
        Have a good day!
  - name: Start httpd service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
    become: true
    become_user: root
